export const API_ERROR_CODES = {
  ACTIVE_ATTRIBUTE_VALUE_REQUIRES_ACTIVE_ATTRIBUTE:
    'ACTIVE_ATTRIBUTE_VALUE_REQUIRES_ACTIVE_ATTRIBUTE',
  ATTRIBUTE_MODIFICATION_NOT_ALLOWED: 'ATTRIBUTE_MODIFICATION_NOT_ALLOWED',
  ATTRIBUTE_VALUE_MODIFICATION_NOT_ALLOWED:
    'ATTRIBUTE_VALUE_MODIFICATION_NOT_ALLOWED',
  CATEGORY_MODIFICATION_NOT_ALLOWED: 'CATEGORY_MODIFICATION_NOT_ALLOWED',
  SUPPLIER_MODIFICATION_NOT_ALLOWED: 'SUPPLIER_MODIFICATION_NOT_ALLOWED',
  UNIT_OF_MEASUREMENT_MODIFICATION_NOT_ALLOWED:
    'UNIT_OF_MEASUREMENT_MODIFICATION_NOT_ALLOWED',
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const API_ERROR_MESSAGES: Record<ApiErrorCode, string> = {
  [API_ERROR_CODES.ACTIVE_ATTRIBUTE_VALUE_REQUIRES_ACTIVE_ATTRIBUTE]:
    'Publish the attribute first to publish its values',
  [API_ERROR_CODES.ATTRIBUTE_MODIFICATION_NOT_ALLOWED]:
    'Active attributes cannot be edited',
  [API_ERROR_CODES.ATTRIBUTE_VALUE_MODIFICATION_NOT_ALLOWED]:
    'Active attribute values cannot be edited',
  [API_ERROR_CODES.CATEGORY_MODIFICATION_NOT_ALLOWED]:
    'Active categories cannot be edited',
  [API_ERROR_CODES.SUPPLIER_MODIFICATION_NOT_ALLOWED]:
    'Cannot edit name or status of an active supplier',
  [API_ERROR_CODES.UNIT_OF_MEASUREMENT_MODIFICATION_NOT_ALLOWED]:
    'Cannot edit name or status of an active unit of measurement',
};
