export const API_ERROR_CODES = {
  ACTIVE_ATTRIBUTE_VALUE_REQUIRES_ACTIVE_ATTRIBUTE:
    'ACTIVE_ATTRIBUTE_VALUE_REQUIRES_ACTIVE_ATTRIBUTE',
  ATTRIBUTE_MODIFICATION_NOT_ALLOWED: 'ATTRIBUTE_MODIFICATION_NOT_ALLOWED',
  ATTRIBUTE_NAME_ALREADY_EXISTS: 'ATTRIBUTE_NAME_ALREADY_EXISTS',
  ATTRIBUTE_VALUE_MODIFICATION_NOT_ALLOWED:
    'ATTRIBUTE_VALUE_MODIFICATION_NOT_ALLOWED',
  CATEGORY_MODIFICATION_NOT_ALLOWED: 'CATEGORY_MODIFICATION_NOT_ALLOWED',
  CATEGORY_NAME_ALREADY_EXISTS: 'CATEGORY_NAME_ALREADY_EXISTS',
  SUPPLIER_MODIFICATION_NOT_ALLOWED: 'SUPPLIER_MODIFICATION_NOT_ALLOWED',
  SUPPLIER_NAME_ALREADY_EXISTS: 'SUPPLIER_NAME_ALREADY_EXISTS',
  UNIT_OF_MEASUREMENT_MODIFICATION_NOT_ALLOWED:
    'UNIT_OF_MEASUREMENT_MODIFICATION_NOT_ALLOWED',
  UNIT_OF_MEASUREMENT_NAME_ALREADY_EXISTS:
    'UNIT_OF_MEASUREMENT_NAME_ALREADY_EXISTS',
  WAREHOUSE_MODIFICATION_NOT_ALLOWED: 'WAREHOUSE_MODIFICATION_NOT_ALLOWED',
  WAREHOUSE_NAME_ALREADY_EXISTS: 'WAREHOUSE_NAME_ALREADY_EXISTS',
} as const;

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

export const API_ERROR_MESSAGES: Record<ApiErrorCode, string> = {
  [API_ERROR_CODES.ACTIVE_ATTRIBUTE_VALUE_REQUIRES_ACTIVE_ATTRIBUTE]:
    'Publish the attribute first to publish its values',
  [API_ERROR_CODES.ATTRIBUTE_MODIFICATION_NOT_ALLOWED]:
    'Active attributes cannot be edited',
  [API_ERROR_CODES.ATTRIBUTE_NAME_ALREADY_EXISTS]:
    'Attribute name already exists.',
  [API_ERROR_CODES.ATTRIBUTE_VALUE_MODIFICATION_NOT_ALLOWED]:
    'Active attribute values cannot be edited',
  [API_ERROR_CODES.CATEGORY_MODIFICATION_NOT_ALLOWED]:
    'Active categories cannot be edited',
  [API_ERROR_CODES.CATEGORY_NAME_ALREADY_EXISTS]:
    'Category name already exists.',
  [API_ERROR_CODES.SUPPLIER_MODIFICATION_NOT_ALLOWED]:
    'Cannot edit name or status of an active supplier',
  [API_ERROR_CODES.SUPPLIER_NAME_ALREADY_EXISTS]:
    'Supplier name already exists.',
  [API_ERROR_CODES.UNIT_OF_MEASUREMENT_MODIFICATION_NOT_ALLOWED]:
    'Cannot edit name or status of an active unit of measurement',
  [API_ERROR_CODES.UNIT_OF_MEASUREMENT_NAME_ALREADY_EXISTS]:
    'Unit name already exists.',
  [API_ERROR_CODES.WAREHOUSE_MODIFICATION_NOT_ALLOWED]:
    'Cannot edit name or status of an active warehouse',
  [API_ERROR_CODES.WAREHOUSE_NAME_ALREADY_EXISTS]:
    'Warehouse name already exists.',
};
