import type { Metadata } from 'next';
import { Barlow, Public_Sans } from 'next/font/google';
import type { ReactNode } from 'react';
import { AppProviders } from './AppProviders';
import { StoreBaseLayout } from '@/components/StoreBaseLayout';
import './globals.css';

const publicSans = Public_Sans({
  variable: '--font-public-sans',
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700', '800'],
});

const barlow = Barlow({
  variable: '--font-barlow',
  subsets: ['latin'],
  display: 'swap',
  weight: ['700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.variable} ${barlow.variable} antialiased`}>
        <AppProviders>
          <StoreBaseLayout>{children}</StoreBaseLayout>
        </AppProviders>
      </body>
    </html>
  );
}
